### ISSUE TITLE
How to execute C# sentences?

### ISSUE THREAD

**Issue by rainssong** [pjc0247/UniScript#2]
Is it possible to execute  C# sentence like other interpreted languages(javascript/lua)？

for example:
```
var src = @"
class PlayerMovement : MonoBehaviour {
    public void MoveForward() {
        transform.position += new Vector3(0, 0, 1);
    }
}
";

var script = CScript.CreateRunner(src);

dynamic move = script
    .Override("PlayerMovement", this)
    .AsDynamic();
move.MoveForward();

```
That's too much for me, what I need is just like this:
```
var src="transform.position += new Vector3(0, 0, 1);"
CScript.execute(src);
```

**Comment by pjc0247** [comment]
@rainssong No, That's not possible in C# (and either my interpreter). 
However, you can write a simple wrapper function like this:

https://github.com/pjc0247/SlowSharp/blob/master/Slowsharp/CScript.cs#L16-L27
